# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Build Windows Binaries

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: windows-latest
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/
    defaults:
      run:
        working-directory: ./server        

    steps:
    - uses: actions/checkout@v4
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
        node-version-file: './server/.nvmrc'
        cache-dependency-path: 'server/package-lock.json'
    - name: version
      uses: jozsefsallai/node-package-version@v1.0.4
      with:
        path: server/package.json
    - uses: benjlevesque/short-sha@v3.0
    - name: install
      run: npm ci
      working-directory: ./server
    - name: build
      run: npm run build:windows
      working-directory: ./server
    - name: archive
      run: Compress-Archive -LiteralPath win -DestinationPath spotify97-server-win64-${{ env.PACKAGE_VERSION }}.zip;dir win;dir
      working-directory: ./server/dist
    - uses: actions/upload-artifact@v4
      with:
        name: windows-binary-${{ env.SHA }}
        path: server/dist/spotify97-server-win64-${{ env.PACKAGE_VERSION }}.zip
  upload:
    runs-on: ubuntu-latest
    steps:
    - name: download
      uses: actions/download-artifact@v4
      with:
        name: windows-binary-${{ env.SHA }}
        path: spotify97-server-win64-${{ env.PACKAGE_VERSION }}.zip
    - run: ls -la
    - name: upload
      uses: appleboy/scp-action@v0.1.7
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USERNAME }}
        port: ${{ secrets.PORT }}
        key: ${{ secrets.KEY }}
        passphrase: ${{ secrets.PASSPHRASE }}
        source: "spotify97-server-win64-${{env.PACKAGE_VERSION}}.zip"
        target: /srv/www/public/spotifyclient97/server/${{ env.PACKAGE_VERSION }}/${{ env.SHA }}/
        strip_components: 2


          
